### ISSUE TITLE
[Multimodal Transfer: A Hierarchical Deep Convolutional Neural Network for Fast Artistic Style Transfer] [[Paper]](https://arxiv.org/pdf/1612.01895.pdf) (CVPR 2017)

### ISSUE THREAD

**Issue by shubhambagwari** [ycjing/Neural-Style-Transfer-Papers#20]
You guys did beautiful work by compiled all NST in a single paper and git page.
I am interested in this paper [Multimodal Transfer: A Hierarchical Deep Convolutional Neural Network for Fast Artistic Style Transfer] [[Paper]](https://arxiv.org/pdf/1612.01895.pdf) (CVPR 2017)
❇️ Code:
[TensorFlow-based](https://github.com/fullfanta/multimodal_transfer)

I was compiling this repo, but I am unable to load the saved model, it is throwing this error 
"[google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'](https://stackoverflow.com/questions/71439124/google-protobuf-message-decodeerror-error-parsing-message-with-type-tensorflow)"
.
Could you help me?

**Comment by ycjing** [comment]
Hi @shubhambagwari 

Thank you for the comments. For the mentioned repo, I remembered that I once run this code successfully several years ago, without the error attached in the your post. I guess it is caused by the incorrect TensorFlow version. Maybe you could try an older version of TensorFlow and run the code again. 

Best,

**Comment by shubhambagwari** [comment]
Yes, It is working. Thank you.
